app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("bases.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("paginas.urls")),
    path("users/", include("usuarios.urls")),
    path("control/", include(("ctrl_comb.urls", "control"), namespace="control")),
]

bases/urls.py
from django.urls import path, include
from .views import *

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("ejemplo", first_view, name="first_view"),
]

ctrl_comb/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("brands", ListBrands.as_view(), name="brand_list"),
    path("brands/save", save_brand, name="save_brand"),
    path("brands/delete/<int:id>", delete_brand, name="delete_brand"),
    path("brands/edit/<int:id>", edit_brand, name="edit_brand"),
    path("models", ListCarModels.as_view(), name="model_list"),
    path("models/create", CreateCarModel.as_view(), name="create_model"),
    path("models/update/<int:pk>", UpdateCarModel.as_view(), name="update_model"),
    path("models/delete/<int:pk>", DeleteCarModel.as_view(), name="delete_model"),
    path(
        "models/create/modal",
        CreateCarModelWithModal.as_view(),
        name="create_model_modal",
    ),
    path(
        "models/update/modal/<int:pk>",
        UpdateCarModelWithModal.as_view(),
        name="update_model_modal",
    ),
    path("models/datatable", datatable_model, name="datatable_model"),
    path("vehicles", ListVehicles.as_view(), name="list_vehicles"),
    path("vehicles/datatable", datatable_vehicle, name="datatable_vehicle"),
    path(
        "vehicles/create/modal",
        CreateVehicleWithModal.as_view(),
        name="create_vehicle_modal",
    ),
    path(
        "vehicles/update/modal/<int:pk>",
        UpdateVehicleWithModal.as_view(),
        name="update_vehicle_modal",
    ),
    path("vehicles/delete/<int:pk>", DeleteVehicle.as_view(), name="delete_vehicle"),
]

paginas/urls.py
from django.urls import path
from .views import *

app_name = "pages"

urlpatterns = [
    path("about", AboutView.as_view(), name="about-app"),
    path("forbidden", ForbiddenView.as_view(), name="forbidden"),
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import *

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path(
        "login-alt/",
        auth_views.LoginView.as_view(template_name="usuarios/login_alt.html"),
        name="login_alt",
    ),
    path("register/", RegisterUserView.as_view(), name="register"),
]

templates/fragments/card-end.html
</div>
</div>

templates/fragments/card-start.html
<div class="card border-danger mb-3" style="width: 80%;">
    <div class="card-header h3">{{ card_header|default:"" }}</div>
    <div class="card-body">

templates/fragments/datatable.html
{% load static %}
<script>
    var tableInfo;
    $(function () {
        tableInfo = $(tableId).DataTable({
            language: {
                url: "{% static 'plugins/datatables/es-CO.json' %}",
            },
            ajax: {
                url: tableUrl,
            },
            columns: tableColumns,
            dom: 'Bfrtip',
            processing: true,
            serverSide: true,
            pageLength: 15
        })
    })

    function deleteCarModel(del_url, id, brand = "", model = "", registration = "", year = "") {
        Swal.fire({
            title: "Estás seguro/a?",
            text: `Deseas eliminar ${brand} ${model} ${registration} ${year}`,
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Sí, Borrar!",
            cancelButtonText: "Cancelar",
        }).then((result) => {
            if (result.isConfirmed) {
                const url = `${del_url}/${id}`
                $.ajax({
                    headers: { "X-CSRFToken": "{{ csrf_token }}" },
                    type: "POST",
                    url,
                    success: (data, textStatus, jqXHR) => {
                        if (jqXHR.status == 200) {
                            Swal.fire({
                                title: "Borrado!",
                                text: `${brand} ${model} ${registration} ${year} ha sido borrado`,
                                icon: "success"
                            }).then(() => { tableInfo.ajax.reload() });
                        }
                    },
                    error: (jqXHR, textStatus, errorThrown) => {
                        Swal.fire({
                            title: "Error!",
                            text: `${brand} ${model} no ha sido borrado`,
                            icon: "error"
                        })
                    },
                })
            }
        });
    }

    $(tableId).on("click", "td.editor-edit", function (event) {
        event.preventDefault()
        const rows = tableInfo.rows(this).data()
        const row = rows["0"]
        const url = `${editUrl}/${row.id}`
        showModal(url)
    })

    $(tableId).on("click", "td.editor-delete", function (event) {
        event.preventDefault()
        const rows = tableInfo.rows(this).data()
        const row = rows["0"]
        const description = row?.description ?? row?.car_model
        deleteCarModel(deleteUrl, row.id, row?.brand, description, row?.registration, row?.year)
    })
</script>

templates/fragments/header.html
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1 id="indicators">{{titulo|default:"Título de la Página"}}</h1>
        </div>
    </div>
</div>

templates/fragments/menu.html
{% load socialaccount %} {% providers_media_js %}

<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="bs-component">
      <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <div
                class="navbar-brand"
                hx-get="{% url 'core:home' %}"
                hx-push-url="true"
                hx-trigger="click"
                hx-target="#body"
                hx-swap="outerHTML"
                style="cursor: pointer;"
            >
            Gas Control
            </div>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarColor01"
            aria-controls="navbarColor01"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <div
                  class="nav-link"
                  hx-get="{% url 'core:home' %}"
                  hx-push-url="true"
                  hx-trigger="click"
                  hx-target="#body"
                  hx-swap="outerHTML"
                  style="cursor: pointer;"
                >
                  Inicio
                </div>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Registrar</a>
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  data-bs-toggle="dropdown"
                  href="#"
                  role="button"
                  aria-haspopup="true"
                  aria-expanded="true"
                >
                Catálogo
                </a>
                <div class="dropdown-menu">
                  <div
                    class="dropdown-item"
                    hx-get="{% url 'control:brand_list' %}"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    style="cursor: pointer;"
                  >
                  Marcas
                  </div>
                  {% if perms.ctrl_comb.view_carmodel %}
                  <a class="dropdown-item" href="{% url 'control:model_list' %}">modelos</a>
                  {% endif %}
                  {% if perms.ctrl_comb.view_vehicle %}
                  <a class="dropdown-item" href="{% url 'control:list_vehicles' %}">Vehículos</a>
                  {% endif %}
                </div>
              </li>
              {% endif %}
              <li class="nav-item">
                <div
                    class="nav-link"
                    hx-get="{% url 'pages:about-app' %}"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    hx-swap="outerHTML"
                    style="cursor: pointer;"
                >
                Acerca de
                </div>
              </li>
            </ul>
            <div class="d-flex">
              {% if user.is_authenticated %}
                <div
                    class="text-info"
                    hx-get="{% url 'users:logout' %}"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    hx-swap="outerHTML"
                    style="cursor: pointer;"
                >
                Cerrar Sesión
                </div>
              {% else %}
                <div
                    class="text-info"
                    hx-get="{% url 'users:login_alt' %}"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    hx-swap="outerHTML"
                    style="cursor: pointer;"
                >
                Iniciar Sesión
                </div> |
                <div
                    class="text-info"
                    hx-get="{% url 'users:register' %}"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    hx-swap="outerHTML"
                    style="cursor: pointer;"
                >
                Regístrate
                </div> |
                <div
                    class="text-info"
                    hx-get="{% provider_login_url 'google' %}?next=/"
                    hx-push-url="true"
                    hx-trigger="click"
                    hx-target="#body"
                    hx-swap="outerHTML"
                    style="cursor: pointer;"
                >
                Google
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>