app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("bases.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("paginas.urls")),
    path("users/", include("usuarios.urls")),
    path("control/", include(("ctrl_comb.urls", "control"), namespace="control")),
]

ctrl_comb/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("brands", ListBrands.as_view(), name="brand_list"),
    path("brands/save", save_brand, name="save_brand"),
    path("brands/delete/<int:id>", delete_brand, name="delete_brand"),
    path("brands/edit/<int:id>", edit_brand, name="edit_brand"),
    path("models", ListCarModels.as_view(), name="model_list"),
    path("models/create", CreateCarModel.as_view(), name="create_model"),
    path("models/update/<int:pk>", UpdateCarModel.as_view(), name="update_model"),
    path("models/delete/<int:pk>", DeleteCarModel.as_view(), name="delete_model"),
    path(
        "models/create/modal",
        CreateCarModelWithModal.as_view(),
        name="create_model_modal",
    ),
    path(
        "models/update/modal/<int:pk>",
        UpdateCarModelWithModal.as_view(),
        name="update_model_modal",
    ),
    path("models/datatable", datatable_model, name="datatable_model"),
    path("vehicles", ListVehicles.as_view(), name="list_vehicles"),
    path("vehicles/datatable", datatable_vehicle, name="datatable_vehicle"),
    path(
        "vehicles/create/modal",
        CreateVehicleWithModal.as_view(),
        name="create_vehicle_modal",
    ),
    path(
        "vehicles/update/modal/<int:pk>",
        UpdateVehicleWithModal.as_view(),
        name="update_vehicle_modal",
    ),
    path("vehicles/delete/<int:pk>", DeleteVehicle.as_view(), name="delete_vehicle"),
]

ctrl_comb/models.py
from django.db import models
from bases.models import BaseModel
from django.urls import reverse


class Brand(BaseModel):
    description = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = "Marca"
        verbose_name_plural = "Marcas"


class CarModel(BaseModel):
    description = models.CharField(
        max_length=50, db_comment="Car model description", verbose_name="Modelo"
    )
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name="Marca")

    def __str__(self):
        return f"{self.brand} - {self.description}"

    class Meta:
        verbose_name = "Modelo"
        verbose_name_plural = "Modelos"
        permissions = [("read_write_permission", "Can read and write car models")]


class Vehicle(BaseModel):
    car_model = models.ForeignKey(
        CarModel, on_delete=models.RESTRICT, verbose_name="Modelo"
    )
    registration = models.CharField(
        max_length=20, help_text="Matricula", verbose_name="Matrícula"
    )
    year = models.PositiveSmallIntegerField(
        help_text="Año del modelo del vehículo", verbose_name="Año"
    )

    def __str__(self):
        return self.registration

    def get_absolute_url(self):
        return reverse("vehicle_edit", kwargs={"pk": self.pk})

    class Meta:
        verbose_name = "Vehículo"
        verbose_name_plural = "Vehículos"
        db_table_comment = "Vehículos"

ctrl_comb/forms.py
from django import forms
from .models import *


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = "__all__"

    def __init__(self, *arg, **kwargs):
        super().__init__(*arg, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({"class": "form-control"})


class CarModelForm(forms.ModelForm):
    class Meta:
        model = CarModel
        fields = ["brand", "description"]


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ["car_model", "registration", "year"]

ctrl_comb/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from django.urls import reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from .models import *
from .forms import *
from bases.views import LoginAndPermissionRequiredMixin, CreateOrModifyMixin


class ListBrands(LoginAndPermissionRequiredMixin, ListView):
    template_name = "ctrl_comb/brand.html"
    model = Brand
    context_object_name = "objects"
    ordering = ["description"]
    login_url = "users:login_alt"
    permission_required = "ctrl_comb.view_brand"


@login_required(login_url="users:login_alt")
def save_brand(request):
    context = {}
    template_name = "ctrl_comb/brand-list.html"

    if request.method == "POST":
        user_id = request.user
        id = request.POST.get("id")
        description = request.POST.get("description")
        brand = None

        if id:
            brand = Brand.objects.filter(id=id).first()
        else:
            brand = Brand.objects.filter(description=description).first()

        if brand:
            brand.description = description
            brand.modified_by = user_id
            brand.save()
        else:
            brand = Brand.objects.create(description=description, created_by=user_id)

    objects = Brand.objects.all().order_by("description")
    context["register"] = brand
    context["objects"] = objects

    return render(request, template_name, context)


@login_required(login_url="users:login_alt")
def delete_brand(request, id):
    context = {}
    template_name = "ctrl_comb/brand-list.html"

    object_to_eliminate = Brand.objects.filter(id=id).first()
    object_to_eliminate.delete()

    objects = Brand.objects.all().order_by("description")
    context["objects"] = objects

    return render(request, template_name, context)


@login_required(login_url="users:login_alt")
def edit_brand(request, id=None):
    context = {}
    template_name = "ctrl_comb/brand-form.html"

    if id:
        object = Brand.objects.filter(id=id).first()
        form = BrandForm(instance=object)
    else:
        form = BrandForm()

    context["form"] = form
    context["object"] = object

    return render(request, template_name, context)


class ListCarModels(LoginAndPermissionRequiredMixin, ListView):
    model = CarModel
    template_name = "ctrl_comb/car-model.html"
    context_object_name = "objects"
    ordering = ["brand", "description"]
    login_url = "users:login_alt"
    permission_required = "ctrl_comb.view_carmodel"
    # permission_required = "ctrl_comb.read_write_permission"


class CreateCarModel(LoginAndPermissionRequiredMixin, CreateOrModifyMixin, CreateView):
    model = CarModel
    template_name = "ctrl_comb/car-model-form.html"
    form_class = CarModelForm
    context_object_name = "object"
    success_url = reverse_lazy("control:model_list")
    permission_required = "ctrl_comb.add_carmodel"


class UpdateCarModel(LoginRequiredMixin, UpdateView):
    model = CarModel
    template_name = "ctrl_comb/car-model-form.html"
    form_class = CarModelForm
    context_object_name = "object"
    success_url = reverse_lazy("control:model_list")
    login_url = "users:login_alt"


class DeleteCarModel(LoginRequiredMixin, DeleteView):
    model = CarModel
    template_name = "bases/delete.html"
    context_object_name = "object"
    success_url = reverse_lazy("control:model_list")
    login_url = "users:login_alt"


class UpdateCarModelWithModal(
    LoginAndPermissionRequiredMixin, CreateOrModifyMixin, UpdateView
):
    model = CarModel
    template_name = "ctrl_comb/car-model-edit-modal.html"
    form_class = CarModelForm
    context_object_name = "object"
    success_url = reverse_lazy("control:model_list")
    permission_required = "ctrl_comb.change_carmodel"


class CreateCarModelWithModal(LoginRequiredMixin, CreateOrModifyMixin, CreateView):
    model = CarModel
    template_name = "ctrl_comb/car-model-edit-modal.html"
    form_class = CarModelForm
    context_object_name = "object"
    success_url = reverse_lazy("control:model_list")


@login_required(login_url="users:login_alt")
@permission_required(perm="ctrl_comb.view_carmodel")
# @permission_required(perm="ctrl_comb.read_write_permission")
def datatable_model(request):
    context = {}
    data = request.GET

    draw = int(data.get("draw"))
    start = int(data.get("start"))
    length = int(data.get("length"))
    search = data.get("search[value]")

    records = CarModel.objects.all()
    records_total = records.count()

    if search:
        records = records.filter(
            Q(brand__description__icontains=search) | Q(description__icontains=search)
        )

    records_filtered = records.count()

    context["draw"] = draw
    context["recordsTotal"] = records_total
    context["recordsFiltered"] = records_filtered

    object_list = records[start : (start + length)]
    paginator = Paginator(object_list, length)

    try:
        objects = paginator.page(draw).object_list
    except PageNotAnInteger:
        objects = paginator.page(int(draw)).object_list
    except EmptyPage:
        objects = paginator.page(paginator.num_pages).object_list

    data_to_send = [
        {
            "id": object.id,
            "brand": object.brand.description,
            "description": object.description,
        }
        for object in objects
    ]

    context["data"] = data_to_send

    return JsonResponse(context, safe=False)


class ListVehicles(LoginAndPermissionRequiredMixin, TemplateView):
    model = Vehicle
    template_name = "ctrl_comb/vehicle.html"
    login_url = "core:home"
    permission_required = "ctrl_comb.view_vehicle"


@login_required(login_url="users:login_alt")
@permission_required(perm="ctrl_comb.view_vehicle")
def datatable_vehicle(request):
    context = {}
    data = request.GET

    draw = int(data.get("draw"))
    start = int(data.get("start"))
    length = int(data.get("length"))
    search = data.get("search[value]")

    if request.user.is_superuser:
        records = Vehicle.objects.all()
    else:
        records = Vehicle.objects.filter(created_by=request.user)

    records_total = records.count()

    if search:
        records = records.filter(
            Q(car_model__brand__description__icontains=search)
            | Q(car_model__description__icontains=search)
            | Q(registration__icontains=search)
            | Q(year__icontains=search)
        )

    records_filtered = records.count()

    context["draw"] = draw
    context["recordsTotal"] = records_total
    context["recordsFiltered"] = records_filtered

    object_list = records[start : (start + length)]
    paginator = Paginator(object_list, length)

    try:
        objects = paginator.page(draw).object_list
    except PageNotAnInteger:
        objects = paginator.page(int(draw)).object_list
    except EmptyPage:
        objects = paginator.page(paginator.num_pages).object_list

    data_to_send = [
        {
            "id": object.id,
            "brand": object.car_model.brand.description,
            "car_model": object.car_model.description,
            "registration": object.registration,
            "year": object.year,
        }
        for object in objects
    ]

    context["data"] = data_to_send

    return JsonResponse(context, safe=False)


class CreateVehicleWithModal(
    LoginAndPermissionRequiredMixin, CreateOrModifyMixin, CreateView
):
    model = Vehicle
    template_name = "ctrl_comb/vehicle-modal.html"
    form_class = VehicleForm
    context_object_name = "object"
    success_url = reverse_lazy("control:list_vehicles")
    permission_required = "ctrl_comb.add_vehicle"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["car_models"] = CarModel.objects.all()
        return context


class UpdateVehicleWithModal(
    LoginAndPermissionRequiredMixin, CreateOrModifyMixin, UpdateView
):
    model = Vehicle
    template_name = "ctrl_comb/vehicle-modal.html"
    form_class = VehicleForm
    context_object_name = "object"
    success_url = reverse_lazy("control:list_vehicles")
    permission_required = "ctrl_comb.change_vehicle"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["car_models"] = CarModel.objects.all()
        return context


class DeleteVehicle(LoginAndPermissionRequiredMixin, DeleteView):
    model = Vehicle
    template_name = "bases/delete.html"
    context_object_name = "object"
    success_url = reverse_lazy("control:list_vehicles")
    permission_required = "ctrl_comb.delete_vehicle"

ctrl_comb/templates/ctrl_comb/brand-form.html
<form
    class="d-flex align-item-center"
    method="post"
    hx-post="{% url 'control:save_brand' %}"
    hx-target="#brand-list"
>
  <fieldset>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="id" class="form-label">Id</label>
          <input
            type="text"
            class="form-control"
            id="id"
            aria-describedby="idhelp"
            name="id"
            placeholder="Id"
            readonly
            value="{{object.id}}"
          />
          <!-- <small id="idhelp" class="form-text text-muted">Id</small> -->
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
            <label for="description" class="form-label">Descripción</label>
            <input
              type="text"
              class="form-control"
              id="description"
              aria-describedby="descriptionhelp"
              name="description"
              placeholder="Descripción"
              value="{{object.description}}"
            />
          <!-- <small id="descriptionhelp" class="form-text text-muted">Descripción</small> -->
          </div>
      </div>
    </div>
    <div class="row">
        <div class="col-md-6 mt-2">
          <button type="submit" class="btn btn-success btn-sm">
          {% if object.id%}
          Editar
          {% else %}
          Guardar
          {% endif %}
          </button>
        </div>
        <div class="col-md-6 mt-2">
            <button
                type="button"
                class="btn btn-info btn-sm"
                hx-get="{% url 'control:brand_list' %}"
                hx-target="#body"
            >
                Limpiar
            </button>
        </div>
    </div>
  </fieldset>
</form>

ctrl_comb/templates/ctrl_comb/brand-list.html
{% if objects %}
<table class="table table-striped table-hover">
    <thead>
        <th>Id</th>
        <th>Descripción</th>
        <th>Acciones</th>
    </thead>
    <tbody>
        {% for object in objects %}
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.description }}</td>
            <td>
                <button type="button" class="btn btn-danger btn-sm">
                    <i class="bi bi-trash3" style="cursor: pointer;" hx-delete="{% url 'control:delete_brand' object.id %}"
                        hx-target="#brand-list" hx-confirm="¿Desea eliminar el registo?"></i>
                </button>
                <button type="button" class="btn btn-success btn-sm">
                    <i class="bi bi-pencil-square" style="cursor: pointer;"
                        hx-get="{% url 'control:edit_brand' object.id %}" hx-target="#brand-form"></i>
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No hay registros</p>
{% endif %}
{% if register %}
<input type="text" class="form-control" id="id" name="id" placeholder="Id" readonly value="{{register.id}}"
    hx-swap-oob="true" />
{% endif %}

ctrl_comb/templates/ctrl_comb/brand.html
{% extends "base.html" %}
{% block titulo %}Marcas{% endblock %}
{% block contenido %}
{% include "fragments/card-start.html" with card_header="Listado de Marcas" %}
<div class="row">
    <div class="col-md-6">
        <div id="brand-form">
            {% include 'ctrl_comb/brand-form.html' %}
        </div>
    </div>
    <div class="col-md-6">
        <div id="brand-list">
            {% include 'ctrl_comb/brand-list.html' %}
        </div>
    </div>
</div>
{% include "fragments/card-end.html" %}
{% endblock %}

{% block js %}
{% include "fragments/datatable.html" with class_name="#brand-table"%}
{% endblock %}

ctrl_comb/templates/ctrl_comb/car-model-edit-modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Agregar/Editar Modelo del Vehículo</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            <div class="modal-body">{{ form|crispy }}</div>
            <div class="modal-footer">
                {% if object.brand %}
                <button type="submit" class="btn btn-success btn-sm">
                    <i class="bi bi-pencil-square"></i>
                    Editar
                </button>
                {% else %}
                <button type="submit" class="btn btn-info btn-sm">
                    <i class="bi bi-floppy"></i>
                    Agregar
                </button>
                {% endif %}
                <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">
                    <i class="bi bi-x-square"></i>
                    Cancelar
                </button>
            </div>
        </form>
    </div>
</div>

ctrl_comb/templates/ctrl_comb/car-model-form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}Agregar/Editar Modelo de Vehículo{% endblock %}
{% block contenido %}
{% include "fragments/card-start.html" with card_header="Agregar/Editar Modelos de Vehículos" %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="row">
        <div class="col-md-6">
            {% if object.brand %}
            <button type="submit" class="btn btn-success btn-sm">
                <i class="bi bi-pencil-square"></i>
                Editar
            </button>
            {% else %}
            <button type="submit" class="btn btn-info btn-sm">
                <i class="bi bi-floppy"></i>
                Agregar
            </button>
            {% endif %}
            <a href="{% url 'control:model_list' %}" class="btn btn-danger btn-sm">
                <i class="bi bi-x-square"></i>
                Cancelar
            </a>
        </div>
    </div>
</form>
{% include "fragments/card-end.html" %}
{% endblock %}

{% block js %}
{% include "fragments/datatable.html" with class_name="#car-model-table"%}
{% endblock %}

ctrl_comb/templates/ctrl_comb/car-model.html
{% extends "base.html" %}
{% block titulo %}Modelos de Vehículos{% endblock %}
{% block contenido %}
{% include "fragments/card-start.html" with card_header="Listado de Modelos de Vehículos" %}
<a href="{% url 'control:create_model' %}" class="btn btn-info btn-sm">
    <i class="bi bi-plus-circle"></i>
    Agregar Modelo
</a>
<button type="button" class="btn btn-secondary btn-sm" onclick="showModal('{% url 'control:create_model_modal' %}')">
    <i class="bi bi-plus-circle"></i>
    Agregar Modelo
</button>
<table id="car-model-table" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Editar</th>
            <th>Borrar</th>
        </tr>
    </thead>
</table>
{% include "fragments/card-end.html" %}
{% endblock %}

{% block js %}
{% endblock %}

<!-- datatable settings for the table on this page -->

<!-- url to get data -->
{% block table_url %}{% url 'control:datatable_model' %}{% endblock %}
<!-- url to edit data -->
{% block edit_url %}/control/models/update/modal{% endblock %}
<!-- url to delete data -->
{% block delete_url %}{% url 'control:model_list' %}/delete{% endblock %}
<!-- table id -->
{% block table_id %}#car-model-table{% endblock %}
<!-- columns to render -->
{% block table_columns %}
{ data: "brand" },
{ data: "description" },
{% endblock table_columns %}

ctrl_comb/templates/ctrl_comb/vehicle-modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Agregar/Editar Vehículo</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            <div class="modal-body">
                <div class="col mb-2">
                    <label for="car_model" class="mb-2">Modelo*</label>
                    <select name="car_model" id="id_model" class="select form-select">
                        <option value="-1">Seleccione un modelo</option>
                        {% for car_model in car_models %}
                        <option value="{{ car_model.id }}">{{ car_model }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{form.registration|as_crispy_field}}
                    </div>
                    <div class="col-6">
                        {{form.year|as_crispy_field}}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                {% if object.car_model.brand %}
                <button type="submit" class="btn btn-success btn-sm">
                    <i class="bi bi-pencil-square"></i>
                    Editar
                </button>
                {% else %}
                <button type="submit" class="btn btn-info btn-sm">
                    <i class="bi bi-floppy"></i>
                    Agregar
                </button>
                {% endif %}
                <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">
                    <i class="bi bi-x-square"></i>
                    Cancelar
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        {% if object %}
        $("#id_model").val("{{ object.car_model.id }}").trigger("change");
        {% endif %}
        $('#id_model').select2({
            theme: 'bootstrap-5',
            dropdownParent: $('.modal-content'),
        });
    });
</script>

ctrl_comb/templates/ctrl_comb/vehicle.html
{% extends "base.html" %}
{% block titulo %}Vehículos{% endblock %}
{% block contenido %}
{% include "fragments/card-start.html" with card_header="Listado de Vehículos" %}
<button type="button" class="btn btn-info btn-sm mb-2" onclick="showModal('{% url 'control:create_vehicle_modal' %}')">
    <i class="bi bi-plus-circle"></i>
    Agregar Vehículo
</button>
<table id="vehicle-table" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Matrícula</th>
            <th>Año</th>
            <th>Editar</th>
            <th>Borrar</th>
        </tr>
    </thead>
</table>
{% include "fragments/card-end.html" %}
{% endblock %}

{% block js %}
{% endblock %}

<!-- datatable settings for the table on this page -->

<!-- url to get data -->
{% block table_url %}{% url 'control:datatable_vehicle' %}{% endblock %}
<!-- url to edit data -->
{% block edit_url %}/control/vehicles/update/modal{% endblock %}
<!-- url to delete data -->
{% block delete_url %}{% url 'control:list_vehicles' %}/delete{% endblock %}
<!-- table id -->
{% block table_id %}#vehicle-table{% endblock %}
<!-- columns to render -->
{% block table_columns %}
{ data: "brand" },
{ data: "car_model" },
{ data: "registration" },
{ data: "year" },
{% endblock table_columns %}